// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC33JBiUks7mbSx0JzhjDlF7woXenNwGwc',
    appId: '1:791092931709:web:f91878b815327380099514',
    messagingSenderId: '791092931709',
    projectId: 'komacrazy-d80a6',
    authDomain: 'komacrazy-d80a6.firebaseapp.com',
    databaseURL: 'https://komacrazy-d80a6-default-rtdb.firebaseio.com',
    storageBucket: 'komacrazy-d80a6.appspot.com',
    measurementId: 'G-SQVFKWL27C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFZVDLwg4zIaejH_IR5vIu7yCaq6AF-vo',
    appId: '1:791092931709:android:e156dee38fcc74dc099514',
    messagingSenderId: '791092931709',
    projectId: 'komacrazy-d80a6',
    databaseURL: 'https://komacrazy-d80a6-default-rtdb.firebaseio.com',
    storageBucket: 'komacrazy-d80a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH81XePqCl2MYZLjrX1ua5Nn9c60EtKF4',
    appId: '1:791092931709:ios:29aa519e81767fa7099514',
    messagingSenderId: '791092931709',
    projectId: 'komacrazy-d80a6',
    databaseURL: 'https://komacrazy-d80a6-default-rtdb.firebaseio.com',
    storageBucket: 'komacrazy-d80a6.appspot.com',
    iosClientId: '791092931709-f6p68mjup7m2sn2a6q7bgot9bct5l3f1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ui1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH81XePqCl2MYZLjrX1ua5Nn9c60EtKF4',
    appId: '1:791092931709:ios:29aa519e81767fa7099514',
    messagingSenderId: '791092931709',
    projectId: 'komacrazy-d80a6',
    databaseURL: 'https://komacrazy-d80a6-default-rtdb.firebaseio.com',
    storageBucket: 'komacrazy-d80a6.appspot.com',
    iosClientId: '791092931709-f6p68mjup7m2sn2a6q7bgot9bct5l3f1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ui1',
  );
}
